<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro"
 	     xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    	 xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
	     name="ball_shooter">
<!--***************************Pluguins***************************-->
<gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
        <robotNamespace>/ball_shooter</robotNamespace>
    </plugin>
</gazebo>
<gazebo>
    <plugin name="p3d_base_controller" filename="libgazebo_ros_p3d.so">
      <robotNamespace>/ball_shooter</robotNamespace>
        <alwaysOn>true</alwaysOn>
        <updateRate>50.0</updateRate>
        <bodyName>base_link</bodyName>
        <topicName>odom</topicName>
        <gaussianNoise>0.01</gaussianNoise>
        <frameName>world</frameName>
        <xyzOffsets>0 0 0</xyzOffsets>
        <rpyOffsets>0 0 0</rpyOffsets>
    </plugin>
</gazebo>
<!--***************************Pluguins***************************-->

<!--***************************Variables***************************-->
<xacro:property name="base_link_length" value="0.1" />
<xacro:property name="base_link_radius" value="0.2" />

<xacro:property name="pan_link_length" value="0.1" />
<xacro:property name="pan_link_radius" value="0.2" />

<xacro:property name="tilt_link_length" value="0.4" />
<xacro:property name="tilt_link_radius" value="0.04" />
<!--***************************Variables***************************-->

<!--***************************Links***************************-->
<!-- base_link -->
<link name="base_link">
  <visual>
    <geometry>
      <cylinder length="${base_link_length}" radius="${base_link_radius}"/>
    </geometry>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <material name="yellow">
      <color rgba="1 1 0 1"/>
    </material>
  </visual>
  <collision>
    <geometry>
      <cylinder length="${base_link_length+0.02}" radius="${base_link_radius}"/>
    </geometry>
    <origin rpy="0 0 0" xyz="0 0 0"/>
  </collision>
  <inertial>
    <mass value="0.1"/>
    <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
  </inertial>
</link>
<!-- pan_link -->
<link name="pan_link">
  <visual>
    <geometry>
      <cylinder length="${pan_link_length}" radius="${pan_link_radius}"/>
    </geometry>
    <origin rpy="0 0 0" xyz="0 0 0."/>
    <material name="blue">
      <color rgba="0 0 1 1"/>
    </material>
  </visual>
  <collision>
    <geometry>
      <cylinder length="${pan_link_length}" radius="${pan_link_radius+0.02}"/>
    </geometry>
    <origin rpy="0 0 0" xyz="0 0 0.09"/>
  </collision>
  <inertial>
    <mass value="1"/>
    <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
  </inertial>
</link>
<!-- camera_link -->
<link name="camera_link">
  <origin xyz="0 0 0.05" rpy="0 0 0" />
  <visual>
    <origin xyz="0 0 0.05" rpy="0 0 0" />
    <geometry>
      <box size="0.1 0.1 0.1"/>
    </geometry>
    <material name="blue"/>
  </visual>
  <collision>
    <origin xyz="0 0 0.05" rpy="0 0 0" />
    <geometry>
      <box size="0.1 0.1 0.1"/>
    </geometry>
  </collision>
  <inertial>
    <origin xyz="0 0 0.05" rpy="0 0 0" />
    <mass value="0.1"/>
  <inertia
    ixx="0.000166667" ixy="0.0" ixz="0.0"
    iyy="0.000166667" iyz="0.0"
    izz="0.000166667"/>
    </inertial>
</link>
<!-- dummy_camera_link -->
<link name="dummy_camera_link">
</link>
<!--***************************Links***************************-->
<!--***************************Joints***************************-->
<!-- pan_joint -->
<joint name="pan_joint" type="revolute">
  <parent link="base_link"/>
  <child link="pan_link"/>
  <origin xyz="0 0 0.1"/>
  <axis xyz="0 0 1" />
  <limit effort="300" velocity="1" lower="-3.14" upper="3.14"/>
  <dynamics damping="50" friction="1"/>
</joint>
<!-- camera_joint -->
<joint name="camera_joint" type="fixed">
  <parent link="pan_link"/>
  <child link="camera_link"/>
  <origin rpy="0 0 0" xyz="0.0 0.0 0.06"/>
  <axis xyz="0 0 0" />
</joint>
<!-- dummy_camera_joint -->
<joint name="dummy_camera_joint" type="fixed">
  <parent link="camera_link"/>
  <child link="dummy_camera_link"/>
  <origin rpy="0 0 0" xyz="0 0 0.05"/>
  <axis xyz="0 0 0" />
</joint>
<!--***************************Joints***************************-->
<!--***************************Gazebo configuration***************************-->
<!-- base_link -->
<gazebo reference="base_link">
  <material>Gazebo/Red</material>
  <turnGravityOff>True</turnGravityOff>
</gazebo>
<!-- pan_link -->
<gazebo reference="pan_link">
    <material>Gazebo/Green</material>
</gazebo>
<!-- dummy_camera_link -->
<gazebo reference="dummy_camera_link">
  <sensor type="camera" name="camera1">
    <update_rate>30</update_rate>
    <always_on>1</always_on>
    <visualize>true</visualize>
  <!-- <pose>0 0 0.05 0 0 0</pose> -->
  <camera name="head">
    <horizontal_fov>1.047</horizontal_fov>
    <image>
      <width>320</width>
      <height>240</height>
      <format>R8G8B8</format>
    </image>
    <clip>
      <near>0.1</near>
      <far>100</far>
    </clip>
  </camera>
  <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
    <alwaysOn>true</alwaysOn>
    <updateRate>0.0</updateRate>
    <cameraName>camera</cameraName>
    <imageTopicName>image_raw</imageTopicName>
    <cameraInfoTopicName>camera_info</cameraInfoTopicName>
    <frameName>camera_link_optical</frameName>
    <!-- setting hackBaseline to anything but 0.0 will cause a misalignment
      between the gazebo sensor image and the frame it is supposed to
      be attached to -->
    <hackBaseline>0.0</hackBaseline>
    <distortionK1>0.0</distortionK1>
    <distortionK2>0.0</distortionK2>
    <distortionK3>0.0</distortionK3>
    <distortionT1>0.0</distortionT1>
    <distortionT2>0.0</distortionT2>
    <CxPrime>0</CxPrime>
    <Cx>0.0</Cx>
    <Cy>0.0</Cy>
    <focalLength>0.0</focalLength>
  </plugin>
  </sensor>
</gazebo>
<!--***************************Gazebo configuration***************************-->
<!--***************************Transmissions***************************-->
<transmission name="pan_joint_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="pan_joint">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="pan_joint_motor">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
</transmission>
</robot>
<!--***************************Transmissions***************************-->
