ball_shooter: #namespace
  launch_running_step: 4 #amount of time the control will be executed
  pan_tilt_running_step: 4 #amount of time the control will be executed

  #bin: used to place the bin in a random position evetytime we reset the world
  max_x_: 5 #maximum position of the xy value
  min_x_: 1 #maximum position of the xy value: this should be higer that the robot size to prevent collision with it
  max_y_: 3 #maximum position of the xy value
  min_y_: 0.3 #maximum position of the xy value: this should be higer that the robot size to prevent collision with it

  #Algorithms parameters
  alpha: 0.1
  gamma: 0.8
  epsilon: 0.9
  epsilon_discount: 0.999 # 1098 eps to reach 0.1
  nepisodes: 300
  nsteps: 1

  n_actions: 16 # number of actions vel_cmd/ angle in deg
  n_actions_ddpg: 2 # number of actions vel_cmd/ angle in deg
  n_states_ddpg: 8
  low_vel_cmd: 4 # minimum speed
  high_vel_cmd: 8 # maximum launch speed
  low_incre_cmd: -30 # move left 180 degrees
  high_incre_cmd: 30

  fixed_pitch:  0.35 # 20 degress
  n_incre_angle: 7
  n_incre_vel: 4

  #normalize vector
  max_pixel_x: 640
  min_pixel_x: 0
  max_pixel_y: 480
  min_pixel_y: 0
  max_w: 1
  min_w: 0
  max_h: 1
  min_h: 0

  #reward
  max_reward: 1000
  num_steps_to_average: 100
  max_succes_rate: 0.85
